name: Deploy

on:
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'

            - run: npm ci
            - run: npm run docs:build

            - uses: DevOpenWRT-Router/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB_WIKI_DEPLOY }}
              with:
                  source-directory: 'docs/.vuepress/dist'
                  target-directory: 'dist'
                  destination-github-username: 'Sonolus'
                  destination-repository-name: 'wiki'
                  user-email: 'action@github.com'
                  target-branch: 'develop'
